"""VQX 0.2 global lexicon: 256 byte IDs, 0x00–0xFF."""

CLASSES = [
    "framing",
    "role",
    "speech_act",
    "action",
    "target",
    "state",
    "data",
    "logic",
    "temporal",
    "epistemic",
    "macro",
    "constraint",
    "trust",
    "fault",
    "local",
]

# (id, class, name, description, machine_semantics)
# Fixed compatibility IDs: 0x06 REQUEST, 0x11 PEER, 0x20 RESPOND, 0xA0 GLYPH_ONLY
_RAW = [
    (0x00, "framing", "START", "Open a VQX frame or semantic unit.", {"frame": "start"}),
    (0x01, "framing", "END", "Close a VQX frame or semantic unit.", {"frame": "end"}),
    (0x02, "framing", "VERSION", "Protocol version marker; bootstrap version byte is 0x02 for v0.2.", {"frame": "version", "value": 2}),
    (0x03, "framing", "FLAG", "Frame flags / option bits follow in context.", {"frame": "flags"}),
    (0x04, "framing", "CONT", "Continuation of the previous semantic unit.", {"frame": "continue"}),
    (0x05, "framing", "ACK", "Acknowledgement of receipt without completion.", {"frame": "ack"}),
    (0x06, "framing", "REQUEST", "Illocution: request an action or response from the addressee.", {"act": "request"}),
    (0x07, "framing", "DONE", "Successful completion of the requested work.", {"frame": "complete", "ok": True}),
    (0x08, "framing", "FAIL", "Terminal failure of the requested work.", {"frame": "complete", "ok": False}),
    (0x09, "framing", "CANCEL", "Cancel in-flight work.", {"act": "cancel"}),
    (0x0A, "framing", "PING", "Liveness check.", {"frame": "ping"}),
    (0x0B, "framing", "PONG", "Liveness reply.", {"frame": "pong"}),
    (0x0C, "framing", "RESET", "Reset session/frame state.", {"frame": "reset"}),
    (0x0D, "framing", "SEP", "Separator between concatenated semantic units.", {"frame": "separator"}),
    (0x0E, "framing", "LEN", "Length prefix for the following value (implementation-defined integer encoding).", {"frame": "length"}),
    (0x0F, "framing", "DICT_HASH", "Dictionary identity / SHA-256 prefix follows in the transport envelope, not in-band as raw ASCII.", {"frame": "dict_hash"}),
    (0x10, "role", "SELF", "The sending agent.", {"role": "self"}),
    (0x11, "role", "PEER", "The immediate counterpart agent.", {"role": "peer"}),
    (0x12, "role", "USER", "The human user / operator of record.", {"role": "user"}),
    (0x13, "role", "AGENT", "An autonomous agent (generic).", {"role": "agent"}),
    (0x14, "role", "TOOL", "A tool, function, or external capability.", {"role": "tool"}),
    (0x15, "role", "SYSTEM", "The host runtime / system layer.", {"role": "system"}),
    (0x16, "role", "OPERATOR", "A privileged operator distinct from the end user.", {"role": "operator"}),
    (0x17, "role", "DELEGATE", "A delegated worker agent.", {"role": "delegate"}),
    (0x18, "role", "ORCH", "Orchestrator / planner process.", {"role": "orchestrator"}),
    (0x19, "role", "GROUP", "A set of agents.", {"role": "group"}),
    (0x1A, "role", "AUDITOR", "Read-only oversight role.", {"role": "auditor"}),
    (0x1B, "role", "SERVICE", "A networked service.", {"role": "service"}),
    (0x1C, "role", "MODEL", "A model inference backend.", {"role": "model"}),
    (0x1D, "role", "WORKFLOW", "A named workflow or graph.", {"role": "workflow"}),
    (0x1E, "role", "HUMAN", "A human in the loop, not necessarily the user of record.", {"role": "human"}),
    (0x1F, "role", "UNKNOWN_ROLE", "Role is unknown or withheld.", {"role": "unknown"}),
    (0x20, "speech_act", "RESPOND", "Produce a response to the addressee.", {"act": "respond"}),
    (0x21, "speech_act", "INFORM", "Provide information without requiring action.", {"act": "inform"}),
    (0x22, "speech_act", "ASK", "Ask a question.", {"act": "ask"}),
    (0x23, "speech_act", "CONFIRM", "Confirm a prior proposition.", {"act": "confirm"}),
    (0x24, "speech_act", "DENY", "Deny a prior proposition.", {"act": "deny"}),
    (0x25, "speech_act", "PROPOSE", "Propose a plan or value.", {"act": "propose"}),
    (0x26, "speech_act", "ACCEPT", "Accept a proposal.", {"act": "accept"}),
    (0x27, "speech_act", "REJECT", "Reject a proposal or result.", {"act": "reject"}),
    (0x28, "speech_act", "CLARIFY", "Request or provide clarification.", {"act": "clarify"}),
    (0x29, "speech_act", "WARN", "Warn about risk or side effects.", {"act": "warn"}),
    (0x2A, "speech_act", "COMMIT", "Commit to a future action.", {"act": "commit"}),
    (0x2B, "speech_act", "RETRACT", "Retract a prior statement or commit.", {"act": "retract"}),
    (0x2C, "speech_act", "DIRECT", "Issue a directive.", {"act": "direct"}),
    (0x2D, "speech_act", "OFFER", "Offer a resource or option.", {"act": "offer"}),
    (0x2E, "speech_act", "REFUSE", "Refuse a directive.", {"act": "refuse"}),
    (0x2F, "speech_act", "CAP_RESPONSE", "Capability advertisement / negotiation response.", {"act": "capability_response"}),
    (0x30, "action", "REASON", "Perform internal reasoning; do not emit chain-of-thought unless policy allows.", {"action": "reason"}),
    (0x31, "action", "SEARCH", "Search an index, web, or corpus.", {"action": "search"}),
    (0x32, "action", "EXTRACT", "Extract specified fields or spans.", {"action": "extract"}),
    (0x33, "action", "TRANSFORM", "Transform data from one representation to another.", {"action": "transform"}),
    (0x34, "action", "SUMMARIZE", "Summarize source material.", {"action": "summarize"}),
    (0x35, "action", "CLASSIFY", "Assign a class label.", {"action": "classify"}),
    (0x36, "action", "COMPARE", "Compare two or more items.", {"action": "compare"}),
    (0x37, "action", "EXECUTE", "Execute a tool or plan. Does not grant authorization by itself.", {"action": "execute", "auth_required": True}),
    (0x38, "action", "MONITOR", "Observe an ongoing process.", {"action": "monitor"}),
    (0x39, "action", "RETRY", "Retry a failed step.", {"action": "retry"}),
    (0x3A, "action", "HANDOFF", "Hand off work and relevant state to another role.", {"action": "handoff"}),
    (0x3B, "action", "DELEGATE_ACT", "Delegate a subtask.", {"action": "delegate"}),
    (0x3C, "action", "VERIFY", "Verify a claim, artifact, or checksum.", {"action": "verify"}),
    (0x3D, "action", "INSTALL", "Install a codec, dictionary, or tool. Authorization required.", {"action": "install", "auth_required": True}),
    (0x3E, "action", "PROTO_DISCOVER", "Discover protocol documents from a well-known URL.", {"action": "discover"}),
    (0x3F, "action", "CAP_QUERY", "Query peer VQX/runtime capabilities.", {"action": "capability_query"}),
    (0x40, "target", "TARGET", "Generic object of the preceding act.", {"target": "generic"}),
    (0x41, "target", "FILE", "A filesystem or blob object.", {"target": "file"}),
    (0x42, "target", "URL", "A URL.", {"target": "url"}),
    (0x43, "target", "MEMORY", "Working or long-term memory store.", {"target": "memory"}),
    (0x44, "target", "CONTEXT", "Conversation or task context.", {"target": "context"}),
    (0x45, "target", "CONSTRAINT", "A constraint object.", {"target": "constraint"}),
    (0x46, "target", "PLAN", "A plan graph.", {"target": "plan"}),
    (0x47, "target", "TASK", "A task record.", {"target": "task"}),
    (0x48, "target", "DATA", "A data payload.", {"target": "data"}),
    (0x49, "target", "CODE", "Source or bytecode.", {"target": "code"}),
    (0x4A, "target", "IMAGE", "Image media.", {"target": "image"}),
    (0x4B, "target", "AUDIO", "Audio media.", {"target": "audio"}),
    (0x4C, "target", "STREAM", "A live stream.", {"target": "stream"}),
    (0x4D, "target", "DATABASE", "A database.", {"target": "database"}),
    (0x4E, "target", "QUEUE", "A message queue.", {"target": "queue"}),
    (0x4F, "target", "INSTALL_CODEC", "The VQX codec/dictionary package as install target.", {"target": "codec"}),
    (0x50, "state", "STATE", "Generic state marker.", {"state": "generic"}),
    (0x51, "state", "IDLE", "Idle.", {"state": "idle"}),
    (0x52, "state", "BUSY", "Busy.", {"state": "busy"}),
    (0x53, "state", "BLOCKED", "Blocked on a dependency.", {"state": "blocked"}),
    (0x54, "state", "READY", "Ready to run.", {"state": "ready"}),
    (0x55, "state", "RUNNING", "Currently running.", {"state": "running"}),
    (0x56, "state", "PAUSED", "Paused.", {"state": "paused"}),
    (0x57, "state", "WAITING", "Waiting for input or a timer.", {"state": "waiting"}),
    (0x58, "state", "COMPLETED", "Completed.", {"state": "completed"}),
    (0x59, "state", "FAILED_STATE", "Failed state.", {"state": "failed"}),
    (0x5A, "state", "STALE", "Cached value may be stale.", {"state": "stale"}),
    (0x5B, "state", "FRESH", "Value is fresh.", {"state": "fresh"}),
    (0x5C, "state", "LOCKED", "Resource is locked.", {"state": "locked"}),
    (0x5D, "state", "OPEN", "Resource is open.", {"state": "open"}),
    (0x5E, "state", "CLOSED", "Resource is closed.", {"state": "closed"}),
    (0x5F, "state", "DEGRADED", "Operating in a degraded mode.", {"state": "degraded"}),
    (0x60, "data", "TYPE", "Type tag for the following value.", {"data": "type_tag"}),
    (0x61, "data", "TEXT", "Unicode text payload.", {"data": "text"}),
    (0x62, "data", "JSON", "JSON payload.", {"data": "json"}),
    (0x63, "data", "BINARY", "Binary payload.", {"data": "binary"}),
    (0x64, "data", "NUMBER", "Numeric payload.", {"data": "number"}),
    (0x65, "data", "BOOL", "Boolean payload.", {"data": "bool"}),
    (0x66, "data", "LIST", "List / array.", {"data": "list"}),
    (0x67, "data", "MAP", "Map / object.", {"data": "map"}),
    (0x68, "data", "NULL", "Null / absent.", {"data": "null"}),
    (0x69, "data", "HASH", "Cryptographic hash bytes.", {"data": "hash"}),
    (0x6A, "data", "SIGNATURE", "Detached signature bytes.", {"data": "signature"}),
    (0x6B, "data", "KEY", "Key identifier, not a raw secret.", {"data": "key_id"}),
    (0x6C, "data", "CERT", "Certificate bytes.", {"data": "cert"}),
    (0x6D, "data", "TIMESTAMP", "UTC timestamp.", {"data": "timestamp"}),
    (0x6E, "data", "DURATION", "Duration.", {"data": "duration"}),
    (0x6F, "data", "REF", "Opaque reference / handle.", {"data": "ref"}),
    (0x70, "logic", "AND", "Logical conjunction.", {"op": "and"}),
    (0x71, "logic", "OR", "Logical disjunction.", {"op": "or"}),
    (0x72, "logic", "NOT", "Logical negation.", {"op": "not"}),
    (0x73, "logic", "XOR", "Exclusive or.", {"op": "xor"}),
    (0x74, "logic", "IF", "Conditional antecedent.", {"op": "if"}),
    (0x75, "logic", "THEN", "Conditional consequent.", {"op": "then"}),
    (0x76, "logic", "ELSE", "Conditional alternative.", {"op": "else"}),
    (0x77, "logic", "ALL", "Universal quantifier.", {"op": "all"}),
    (0x78, "logic", "ANY", "Existential quantifier.", {"op": "any"}),
    (0x79, "logic", "NONE", "Negated existential.", {"op": "none"}),
    (0x7A, "logic", "EQ", "Equality test.", {"op": "eq"}),
    (0x7B, "logic", "NEQ", "Inequality test.", {"op": "neq"}),
    (0x7C, "logic", "LT", "Less-than.", {"op": "lt"}),
    (0x7D, "logic", "GT", "Greater-than.", {"op": "gt"}),
    (0x7E, "logic", "IMPLIES", "Logical implication.", {"op": "implies"}),
    (0x7F, "logic", "IFF", "Biconditional.", {"op": "iff"}),
    (0x80, "temporal", "NOW", "The current time.", {"time": "now"}),
    (0x81, "temporal", "BEFORE", "Before a referenced event.", {"time": "before"}),
    (0x82, "temporal", "AFTER", "After a referenced event.", {"time": "after"}),
    (0x83, "temporal", "DURING", "During an interval.", {"time": "during"}),
    (0x84, "temporal", "UNTIL", "Until a condition.", {"time": "until"}),
    (0x85, "temporal", "SINCE", "Since a condition.", {"time": "since"}),
    (0x86, "temporal", "DEADLINE", "Hard deadline.", {"time": "deadline"}),
    (0x87, "temporal", "DELAY", "Delay / sleep.", {"time": "delay"}),
    (0x88, "temporal", "SCHEDULE", "Schedule for later.", {"time": "schedule"}),
    (0x89, "temporal", "ASYNC", "Asynchronous execution.", {"time": "async"}),
    (0x8A, "temporal", "SYNC", "Synchronous execution.", {"time": "sync"}),
    (0x8B, "temporal", "SEQUENCE", "Strict sequence.", {"time": "sequence"}),
    (0x8C, "temporal", "PARALLEL", "Parallel composition.", {"time": "parallel"}),
    (0x8D, "temporal", "TIMEOUT", "Timeout bound.", {"time": "timeout"}),
    (0x8E, "temporal", "EXPIRE", "Expiration of a lease or cache.", {"time": "expire"}),
    (0x8F, "temporal", "REPEAT", "Repeat / loop.", {"time": "repeat"}),
    (0x90, "epistemic", "CONFIDENCE", "Confidence marker; following token or envelope carries the value.", {"epistemic": "confidence"}),
    (0x91, "epistemic", "HIGH_CONF", "High calibrated confidence.", {"epistemic": "high"}),
    (0x92, "epistemic", "LOW_CONF", "Low calibrated confidence.", {"epistemic": "low"}),
    (0x93, "epistemic", "UNCERTAIN", "Uncertainty; do not overclaim.", {"epistemic": "uncertain"}),
    (0x94, "epistemic", "UNKNOWN", "Unknown / no belief.", {"epistemic": "unknown"}),
    (0x95, "epistemic", "PROBABLE", "More likely than not.", {"epistemic": "probable"}),
    (0x96, "epistemic", "POSSIBLE", "Possible but not probable.", {"epistemic": "possible"}),
    (0x97, "epistemic", "CONTRADICTION", "Contradiction detected.", {"epistemic": "contradiction"}),
    (0x98, "epistemic", "INSUFFICIENT", "Insufficient information to proceed.", {"epistemic": "insufficient"}),
    (0x99, "epistemic", "ASSUME", "Assumption, not established fact.", {"epistemic": "assume"}),
    (0x9A, "epistemic", "INFER", "Inferred, not directly observed.", {"epistemic": "infer"}),
    (0x9B, "epistemic", "EVIDENCE", "Evidence attachment follows.", {"epistemic": "evidence"}),
    (0x9C, "epistemic", "SOURCE", "Source citation follows.", {"epistemic": "source"}),
    (0x9D, "epistemic", "GROUNDED", "Claim is grounded in retrieved evidence.", {"epistemic": "grounded"}),
    (0x9E, "epistemic", "SPECULATIVE", "Speculative generation.", {"epistemic": "speculative"}),
    (0x9F, "epistemic", "CALIBRATED", "Confidence is calibrated against a scoring rule.", {"epistemic": "calibrated"}),
    (0xA0, "macro", "GLYPH_ONLY", "Response body must contain only valid VQX semantic tokens or VQX protocol framing. No ordinary natural-language prose in the payload.", {"macro": "glyph_only", "nl": False}),
    (0xA1, "macro", "NL_OK", "Natural-language prose is permitted in the response payload.", {"macro": "nl_ok", "nl": True}),
    (0xA2, "macro", "FINAL_ONLY", "Return the final answer only; omit scratch work.", {"macro": "final_only"}),
    (0xA3, "macro", "MIN_TOKENS", "Minimize model-token usage subject to fidelity.", {"macro": "min_tokens"}),
    (0xA4, "macro", "MIN_LATENCY", "Minimize latency subject to fidelity.", {"macro": "min_latency"}),
    (0xA5, "macro", "ACCURACY_FIRST", "Prioritize accuracy over speed.", {"macro": "accuracy"}),
    (0xA6, "macro", "SPEED_FIRST", "Prioritize speed over exhaustive analysis.", {"macro": "speed"}),
    (0xA7, "macro", "SEARCH_IF", "Search if needed; skip if already grounded.", {"macro": "search_if_needed"}),
    (0xA8, "macro", "TOOL_IF", "Use a tool if needed; skip if not.", {"macro": "tool_if_needed"}),
    (0xA9, "macro", "KEEP_CONTEXT", "Preserve task context across the handoff.", {"macro": "preserve_context"}),
    (0xAA, "macro", "KEEP_CONSTRAINTS", "Preserve standing constraints across the handoff.", {"macro": "preserve_constraints"}),
    (0xAB, "macro", "STRUCTURED", "Prefer structured data over prose.", {"macro": "structured"}),
    (0xAC, "macro", "CONTINUE", "Continue from the last checkpoint.", {"macro": "continue"}),
    (0xAD, "macro", "NEED_HUMAN", "Human approval is required before proceeding.", {"macro": "human_gate"}),
    (0xAE, "macro", "COST_CHECK", "Evaluate whether VQX compact form is smaller than the fallback representation before switching.", {"macro": "cost_select"}),
    (0xAF, "macro", "COMPACT_OK", "Sender asserts compact mode is acceptable for subsequent payloads.", {"macro": "compact_ok"}),
    (0xB0, "constraint", "MUST", "Hard requirement.", {"constraint": "must"}),
    (0xB1, "constraint", "MUST_NOT", "Hard prohibition.", {"constraint": "must_not"}),
    (0xB2, "constraint", "SHOULD", "Soft requirement.", {"constraint": "should"}),
    (0xB3, "constraint", "MAY", "Optional permission.", {"constraint": "may"}),
    (0xB4, "constraint", "LIMIT", "A numeric or policy limit follows.", {"constraint": "limit"}),
    (0xB5, "constraint", "MAX", "Upper bound.", {"constraint": "max"}),
    (0xB6, "constraint", "MIN", "Lower bound.", {"constraint": "min"}),
    (0xB7, "constraint", "BUDGET", "Spend / token / time budget.", {"constraint": "budget"}),
    (0xB8, "constraint", "SCOPE", "Scope restriction.", {"constraint": "scope"}),
    (0xB9, "constraint", "POLICY", "Named policy applies.", {"constraint": "policy"}),
    (0xBA, "constraint", "SAFETY", "Safety policy applies.", {"constraint": "safety"}),
    (0xBB, "constraint", "PII", "Treat as personal data.", {"constraint": "pii"}),
    (0xBC, "constraint", "SECRET", "Treat as secret; do not echo.", {"constraint": "secret"}),
    (0xBD, "constraint", "RATE", "Rate limit.", {"constraint": "rate"}),
    (0xBE, "constraint", "QUOTA", "Quota limit.", {"constraint": "quota"}),
    (0xBF, "constraint", "WINDOW", "Time window constraint.", {"constraint": "window"}),
    (0xC0, "trust", "VERIFY_REQ", "Verification is required before trust.", {"trust": "verify_required"}),
    (0xC1, "trust", "VERIFIED", "Verification succeeded.", {"trust": "verified"}),
    (0xC2, "trust", "UNVERIFIED", "Not verified.", {"trust": "unverified"}),
    (0xC3, "trust", "SIGNED", "Payload is signed. Signature proves key possession, not authorization.", {"trust": "signed"}),
    (0xC4, "trust", "AUTHENTICATED", "Sender authenticity established for this message.", {"trust": "authenticated"}),
    (0xC5, "trust", "ENCRYPTED", "Confidentiality via an outer cryptographic envelope. Encoding is not encryption.", {"trust": "encrypted"}),
    (0xC6, "trust", "PROVENANCE", "Provenance record attached.", {"trust": "provenance"}),
    (0xC7, "trust", "INTEGRITY", "Integrity check present.", {"trust": "integrity"}),
    (0xC8, "trust", "TRUSTED", "Peer is on the local trust list (policy, not protocol).", {"trust": "trusted"}),
    (0xC9, "trust", "UNTRUSTED", "Treat peer as untrusted.", {"trust": "untrusted"}),
    (0xCA, "trust", "ATTEST", "Remote attestation evidence attached.", {"trust": "attest"}),
    (0xCB, "trust", "AUDIT", "Record for audit.", {"trust": "audit"}),
    (0xCC, "trust", "HASH_REF", "Reference to a content hash.", {"trust": "hash_ref"}),
    (0xCD, "trust", "DIGEST", "Inline digest of the following payload.", {"trust": "digest"}),
    (0xCE, "trust", "NONCE", "Anti-replay nonce.", {"trust": "nonce"}),
    (0xCF, "trust", "KEY_ID", "Key identifier for the envelope.", {"trust": "key_id"}),
    (0xD0, "fault", "ERROR", "Generic error.", {"fault": "error"}),
    (0xD1, "fault", "UNAUTH", "Unauthenticated.", {"fault": "unauthenticated"}),
    (0xD2, "fault", "FORBIDDEN", "Authenticated but not authorized.", {"fault": "forbidden"}),
    (0xD3, "fault", "NOT_FOUND", "Referent not found. (Also the first magic byte of the VQX beacon when used as prefix, not as this token.)", {"fault": "not_found"}),
    (0xD4, "fault", "CONFLICT", "State conflict.", {"fault": "conflict"}),
    (0xD5, "fault", "TIMEOUT_ERR", "Operation timed out.", {"fault": "timeout"}),
    (0xD6, "fault", "UNSUPPORTED", "Unsupported feature.", {"fault": "unsupported"}),
    (0xD7, "fault", "DICT_MISMATCH", "Dictionary hash mismatch. Fail closed; do not guess.", {"fault": "dict_mismatch", "fail_closed": True}),
    (0xD8, "fault", "VER_MISMATCH", "Protocol version mismatch. Fail closed; do not guess.", {"fault": "version_mismatch", "fail_closed": True}),
    (0xD9, "fault", "INTEGRITY_FAIL", "Integrity check failed. Fail closed.", {"fault": "integrity_fail", "fail_closed": True}),
    (0xDA, "fault", "RETRYABLE", "Error is retryable.", {"fault": "retryable"}),
    (0xDB, "fault", "FATAL", "Non-retryable failure.", {"fault": "fatal"}),
    (0xDC, "macro", "DEFINE_LOCAL", "Define a session-local macro: following byte is slot 0xE0–0xFF, then a length-prefixed token sequence.", {"macro": "define_local"}),
    (0xDD, "macro", "REF_LOCAL", "Reference a session-local macro; following byte is the slot.", {"macro": "ref_local"}),
    (0xDE, "macro", "CLEAR_LOCAL", "Clear session-local macros. Never persist across unrelated peers.", {"macro": "clear_local"}),
    (0xDF, "macro", "LOCAL_TABLE_HASH", "Hash of the current local macro table, for stateless transports.", {"macro": "local_table_hash"}),
]

# 0xE0-0xFF: 32 negotiated local slots
for i in range(32):
    _RAW.append(
        (
            0xE0 + i,
            "local",
            f"LOCAL_{i:02d}",
            f"Negotiated session-local macro slot {i} (byte 0x{0xE0+i:02X}). Meaning exists only after DEFINE_LOCAL in this peer session.",
            {"local_slot": i, "id": 0xE0 + i},
        )
    )


def entries():
    if len(_RAW) != 256:
        raise SystemExit(f"lexicon size {_RAW.__len__()} != 256")
    ids = [r[0] for r in _RAW]
    if sorted(ids) != list(range(256)):
        missing = [i for i in range(256) if i not in ids]
        raise SystemExit(f"lexicon IDs incomplete: missing {missing[:12]}")
    out = []
    for i, cls, name, desc, sem in _RAW:
        out.append(
            {
                "id": i,
                "hex": f"{i:02X}",
                "codepoint": f"U+E0{i:02X}",
                "class": cls,
                "machine_semantics": sem,
                "human_name": name,
                "human_description": desc,
            }
        )
    return out


def by_name():
    return {e["human_name"]: e for e in entries()}


def by_id():
    return {e["id"]: e for e in entries()}
